name: "Pipe Terraform"

on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  terraform:
      permissions: write-all
      uses: "yagoalmeida/terraform_actions/.github/workflows/terraform_actions.yaml@main"
      with:
        tf_version: "1.0.9"
        os_version: "ubuntu-20.04"
        use_infracost: true
      secrets:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}
